### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by alexsshoelovers** [vsoch/django-nginx-upload#1]
Hi! I was trying to test the app but I think the repo is missing some files, initially the ones that return 404 are:  style.css and selector.js  I noted static/ is in the .gitignore

**Comment by vsoch** [comment]
Oups, sorry about that! Yes, I definitely just totally missed them :) Give it a try now, just added them!
https://github.com/vsoch/django-nginx-upload/tree/master/upload/main/static
