### ISSUE TITLE
Unable to upload a file - 503 Error - No such file or directory

### ISSUE THREAD

**Issue by ThomasCarca** [vsoch/django-nginx-upload#4]
Hello,
thank you very much for this awesome tutorial, I am facing a very similar use case where I need large files uploaded to a server running django, so this is definitely appreciated !

I have successfully started all 3 containers and was able to reach the webserver through localhost. When trying to upload a file it immediately fails and display a 503 Service Temporarily Unavailable error.
Going through the logs, I've noticed this : 
```
nginx_1   | 2019/07/31 14:23:54 [error] 6#6: *2 failed to create output file "/var/www/images/_upload/1/0000000001" for "database.png" (2: No such file or directory), client: 172.17.0.1, server: localhost, request "POST /upload HTTP/1.1", host: "localhost", referrer: "http://localhost/"
```

Any idea what could be causing this ?

**Comment by vsoch** [comment]
That tells you that the path where it uploads to doesn't exist. Try shelling into the nginx container and inspecting that area - likely these paths are missing:

https://github.com/vsoch/django-nginx-upload/blob/master/nginx/Dockerfile#L13

Let me know what you find!

**Comment by vsoch** [comment]
There also should be a much easier way to create those paths:

```bash
mkdir -p /var/www/images/_upload/{0..9}
```

**Comment by vsoch** [comment]
Also see https://github.com/vsoch/django-nginx-upload/blob/master/Dockerfile#L29 If they exist it might be a permissions error. But I don't know why it wouldn't work for you when it worked for me.

**Comment by ThomasCarca** [comment]
You were right these directories do not exist. I really wonder why because the logs of the nginx image being built does not seem to display any weird behavior. After creating these directories manually, it works as expected.

I have tried several steps, none worked :
- Remove all containers and run new ones
- Remove all images and build new ones
- Remove the project and start from scratch

```
Docker version 1.13.1, build b2f74b2/1.13.1
docker-compose version 1.18.0, build 8dd22a9 
```

On a side note, I was unable to successfully use the following command from the container shell:
`mkdir -p /var/www/images/_upload/{0..9}`
Weirdly enough, it creates one directory "{0..9}" instead of the expected multiple directories.
Is it due to the fact i am running this command :
`docker exec -it <container_id> /bin/sh` and not `docker exec -it <container_id> /bin/bash` ?

Thank you for your **very** quick answer, your help is very much appreciated !

**Comment by vsoch** [comment]
It could be that a cache was used for the build, and the directories weren't created. You could always build the image manually with just docker and the `--no-cache` flag to test, in case it's related to docker-compose.

Ah, so the command I gave won't work if nginx has a shell (sh) base - expansion is supported by shells like bash (and in retrospect this is likely why I wrote the recipe as it currently is). The quick fix is just to shell into the nginx container after creation and create those directories.

**Comment by vsoch** [comment]
fwiw, I'm getting weird errors now with exposing the port, but I do a lot of hacky things on my machine so I think it's more likely I've introduced an issue with networking and docker.

**Comment by ThomasCarca** [comment]
Okay I've got something working.
I found [this issue](https://stackoverflow.com/questions/52754149/operation-of-the-mkdir-command-with-dockerfile) which looked pretty similar. The top answer actually solves our problem. 

> Fix: Either you remove the volume from your docker-compose.yml or you create the directories on the host before starting the container.

After creating the directories on the host machine under django-nginx-upload/images/_upload, I can see them under /var/www/images/_upload in the nginx container.

**Comment by vsoch** [comment]
Oy, that has me worried for future reliability of docker-compose! To be extra careful, could you share the versions of the postgres you are using, and confirm the others are still:

```
Docker version 1.13.1, build b2f74b2/1.13.1
docker-compose version 1.18.0, build 8dd22a9 
```
I guess docker-compose is being abandoned for Kubernetes and similar, but it's a shame because they are much harder to use.

**Comment by ThomasCarca** [comment]
Yes, I confirm these are the version of docker and docker-compose I am currently using. As for postgres, it's pulling the latest version from docker.io.

**Comment by vsoch** [comment]
Thanks @ThomasCarca ! I'm glad it's working and I apologize my system is a little broken so I couldn't help more than superficially. If it does help, I just put together the entire thing with a different container technology (Singularity) which is optimized for HPC / read only. https://twitter.com/vsoch/status/1156946405623308289

If you are good, then feel free to close the issue.

**Comment by ThomasCarca** [comment]
Thanks for your time, your help was valuable, I'll have a look at your work !

Closing now
