### ISSUE TITLE
Avoid page refresh on form submit

### ISSUE THREAD

**Issue by tomaso909** [vsoch/django-nginx-upload#6]
Thanks for sharing this ! I got the example working and then modified it to suit my needs in no time.

I'm am now trying to modify it further so that the page does not refresh when I submit the form. To avoid the page refresh I'd usually send the form data through an ajax request and then parse it in a Django view. However in this case the ajax request is sent to the /upload location of Nginx and I haven't been able to make it work. This is what I have so far:

This is what gets called when I submit the form:
```
    $.ajax({
        type:'POST',
        url:'/upload',    // Target nginx location.
        dataType:'json',
        data:{
            file:$('#file').val(),
            csrfmiddlewaretoken: '{{ csrf_token }}'
        },
        success:function(response) {
            console.log('works')
        }
    })
```

The html form tag remains fairly similar:
`<form id="uploadGeometriesForm" onsubmit="return false;" method="POST" enctype="multipart/form-data">`

Unfortunately I'm getting a 415 error: Unsupported media type.

![Screenshot from 2019-11-13 18-10-32](https://user-images.githubusercontent.com/9213551/68787049-18fb8880-0641-11ea-99bb-48b7b1e2950a.png)

Does Nginx require a different request format, additional fields, or a different header ?. Maybe I have to change something else on the form html tag. I though that maybe you could think of a solution.

**Comment by vsoch** [comment]
You are just trying to recreate the POST with the form using ajax instead?  I can't debug this for you, but I think you'd want to follow the headers outlined [here](http://www.grid.net.ru/nginx/resumable_uploads.en.html) and a good way to debug would be to edit the code to print verbose statements for all headers fields when it works, and then print what you get when you try with Ajax.

**Comment by tomaso909** [comment]
Thanks for the link !
I tried for a while but I eventually gave up and now I just open a new window with the upload form which then gets closed onSubmit.
I close the issue since it is not really a problem of your library.

**Comment by vsoch** [comment]
Good luck! This is one of those things that as long as you keep trying things, you'll eventually figure it out :)

**Comment by tomaso909** [comment]
I managed to do it.
This is the request with Fetch API (instead of ajax):
```
fetch('/upload', {
    method: 'post',
    body: new FormData(document.getElementById('form-id')),
}).then(...)
```
Pretty easy. My problem is that I was passing the "Content-Type":"multipart/form-data"  header but it must not be passed, as specified in the link you provided. Also, initially I was not sending a FormData object.

**Comment by vsoch** [comment]
Oh interesting, multipart form data is usually required for file uploads. Anyway, I'm really glad that you figured it out! :clinking_glasses:
